# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gillespie's Direct Method in C++
#' 
#' Simulate a trajectory from a stochastic petri net model.
#' 
#' @param M0 the initial marking of the net
#' @param tmax the maximum simulation time
#' @param pars a named list of parameters to pass to \code{haz}
#' @param haz an R function that takes 3 arguments (time, state, pars) and returns a vector of hazards for each event
#' @param seed a positive integer seed for the random number generator (\url{http://www.cplusplus.com/reference/random/})
#' @param info print information on simulation every \code{info} events
#' @param prealloc how much memory to preallocate for output
#' 
#' @examples
#' \dontrun{
#' library(gillespieCXX)
#' library(ggplot2)
#' library(reshape2)
#' data(SIR)
#' out <- gillespie_dm(M0 = SIR$M0,tmax = 250,pars = SIR$pars,haz = SIR$hazard,seed = 12214L,info = 100)
#' out <- as.data.frame(out)
#' ggplot(data = melt(out,id.vars="time")) +
#'   geom_line(aes(x=time,y=value,color=variable)) +
#'   theme_bw()
#' }
#' 
#' @export
gillespie_dm <- function(M0, tmax, pars, haz, seed, info = 100L, prealloc = 1e4L) {
    .Call('_gillespieCXX_gillespie_dm', PACKAGE = 'gillespieCXX', M0, tmax, pars, haz, seed, info, prealloc)
}

